runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  DATABASE_URL: "mongodb+srv://lms-user:lms123@workshop-dev.spjcvpy.mongodb.net/?retryWrites=true&w=majority"
  DATABASE_NAME: "workshop-dev"
  DATABASE_USERNAME: "lms-user"
  DATABASE_PASSWORD: "lms123"

  # AUTH
  AUTH_ISSUER: "workshop"
  AUTH_SECRET_KEY: "secret123"

  # CLOUDINARY

  CLD_API_KEY: 761362853125772
  CLD_API_SECRET: "Gy4dHtJghQB1s6e55cKwNfD_4yY"
  CLD_NAME: "dvr8rswvg"
  CLOUDINARY_URL: "cloudinary://761362853125772:Gy4dHtJghQB1s6e55cKwNfD_4yY@dvr8rswvg"